# Generated by Django 3.0.8 on 2022-09-29 13:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('c_surname', models.CharField(max_length=100, verbose_name='Surname')),
                ('c_name', models.CharField(max_length=100, verbose_name='Name')),
                ('position_level', models.CharField(max_length=100, verbose_name='Position Level')),
                ('position', models.CharField(max_length=100, verbose_name='Going For')),
                ('party', models.CharField(max_length=100, verbose_name='Party')),
                ('c_state', models.CharField(blank=True, max_length=100, null=True, verbose_name='State')),
                ('c_lga', models.CharField(blank=True, max_length=100, null=True, verbose_name='Local Government')),
                ('image', models.ImageField(upload_to='uploads/', verbose_name='Post Image')),
                ('mani_file', models.FileField(upload_to='uploads/', verbose_name='Post Image')),
                ('description', models.TextField(max_length=500, verbose_name='More Information about the Candidate')),
                ('email', models.EmailField(max_length=100)),
                ('number', models.PositiveIntegerField()),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('surname', models.CharField(max_length=100, verbose_name='Surname')),
            ],
        ),
    ]
