# Generated by Django 3.0.8 on 2022-09-29 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table='dbuser',
        ),
    ]
